// <auto-generated />
using Com.DanLiris.Service.Gline.Lib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Com.DanLiris.Service.Gline.Lib.Migrations
{
    [DbContext(typeof(GlineDbContext))]
    [Migration("20230512013425_UpdateTransaksiQcNullableColumn")]
    partial class UpdateTransaksiQcNullableColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.MasterModel.Line", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("kode_unit")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("nama_gedung")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("nama_line");

                    b.Property<string>("nama_unit")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.MasterModel.Proses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("cycle_time");

                    b.Property<string>("nama_proses")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Proses");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.ReworkModel.Rework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<Guid>("id_line");

                    b.Property<Guid>("id_ro");

                    b.Property<int>("nama_line");

                    b.Property<string>("nama_operator")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("npk")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("qty_rework");

                    b.Property<string>("rono")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Rework");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.ReworkModel.ReworkTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<Guid>("id_rework");

                    b.Property<TimeSpan>("jam_akhir");

                    b.Property<TimeSpan>("jam_awal");

                    b.Property<string>("nama_operator")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("npk")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("ReworkTime");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.SettingRoModel.SettingRo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("artikel")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<Guid>("id_line");

                    b.Property<int>("jam_target");

                    b.Property<string>("kode_unit")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("nama_gedung")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("nama_line");

                    b.Property<string>("nama_unit")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("quantity");

                    b.Property<string>("rono")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("setting_date");

                    b.Property<TimeSpan>("setting_time");

                    b.Property<double>("smv");

                    b.HasKey("Id");

                    b.ToTable("SettingRo");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.TransaksiModel.SummaryOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<Guid>("id_proses");

                    b.Property<Guid>("id_ro");

                    b.Property<int>("jml_pass_per_ro");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("nama_proses")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("npk")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("rono")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("setting_date");

                    b.Property<int>("total_rework");

                    b.Property<TimeSpan>("total_waktu_pengerjaan");

                    b.HasKey("Id");

                    b.ToTable("SummaryOperator");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.TransaksiModel.SummaryQc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("npk")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("rono")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("setting_date");

                    b.Property<TimeSpan>("setting_time");

                    b.Property<int>("total_pass");

                    b.Property<int>("total_reject");

                    b.HasKey("Id");

                    b.ToTable("SummaryQc");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.TransaksiModel.TransaksiOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("cycle_time");

                    b.Property<string>("employee_role")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("id_line");

                    b.Property<Guid>("id_proses");

                    b.Property<Guid>("id_setting_ro");

                    b.Property<Guid>("id_shift");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("nama_line");

                    b.Property<string>("nama_proses")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("nama_shift")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("npk")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<bool>("pass");

                    b.Property<TimeSpan>("pass_time");

                    b.Property<int>("quantity");

                    b.Property<string>("rono")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("setting_date");

                    b.Property<TimeSpan>("setting_time");

                    b.HasKey("Id");

                    b.ToTable("TransaksiOperator");
                });

            modelBuilder.Entity("Com.DanLiris.Service.Gline.Lib.Models.TransaksiModel.TransaksiQc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("CreatedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedUtc");

                    b.Property<string>("DeletedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("DeletedUtc");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastModifiedAgent")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("LastModifiedUtc");

                    b.Property<double>("cycle_time");

                    b.Property<string>("employee_role")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<Guid>("id_line");

                    b.Property<Guid?>("id_proses");

                    b.Property<Guid?>("id_proses_reject");

                    b.Property<Guid>("id_setting_ro");

                    b.Property<Guid>("id_shift");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("nama_line");

                    b.Property<string>("nama_proses")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("nama_proses_reject");

                    b.Property<string>("nama_reject")
                        .HasMaxLength(32);

                    b.Property<string>("nama_shift")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("npk")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("npk_reject")
                        .HasMaxLength(32);

                    b.Property<bool?>("pass");

                    b.Property<TimeSpan?>("pass_time");

                    b.Property<int>("quantity");

                    b.Property<bool?>("reject");

                    b.Property<TimeSpan?>("reject_time");

                    b.Property<string>("rono")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("setting_date");

                    b.Property<TimeSpan>("setting_time");

                    b.HasKey("Id");

                    b.ToTable("TransaksiQc");
                });
#pragma warning restore 612, 618
        }
    }
}
